// Roboto
import '@fontsource/roboto/100.css'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import '@fontsource/roboto/900.css'

import '@fontsource/roboto/100-italic.css'
import '@fontsource/roboto/300-italic.css'
import '@fontsource/roboto/400-italic.css'
import '@fontsource/roboto/500-italic.css'
import '@fontsource/roboto/700-italic.css'
import '@fontsource/roboto/900-italic.css'

// Barlow Condensed
import '@fontsource/barlow-condensed/100.css'
import '@fontsource/barlow-condensed/200.css'
import '@fontsource/barlow-condensed/300.css'
import '@fontsource/barlow-condensed/400.css'
import '@fontsource/barlow-condensed/500.css'
import '@fontsource/barlow-condensed/600.css'
import '@fontsource/barlow-condensed/700.css'
import '@fontsource/barlow-condensed/800.css'
import '@fontsource/barlow-condensed/900.css'

import '@fontsource/barlow-condensed/100-italic.css'
import '@fontsource/barlow-condensed/200-italic.css'
import '@fontsource/barlow-condensed/300-italic.css'
import '@fontsource/barlow-condensed/400-italic.css'
import '@fontsource/barlow-condensed/500-italic.css'
import '@fontsource/barlow-condensed/600-italic.css'
import '@fontsource/barlow-condensed/700-italic.css'
import '@fontsource/barlow-condensed/800-italic.css'
import '@fontsource/barlow-condensed/900-italic.css'

// Barlow Semi Condensed
import '@fontsource/barlow-semi-condensed/100.css'
import '@fontsource/barlow-semi-condensed/200.css'
import '@fontsource/barlow-semi-condensed/300.css'
import '@fontsource/barlow-semi-condensed/400.css'
import '@fontsource/barlow-semi-condensed/500.css'
import '@fontsource/barlow-semi-condensed/600.css'
import '@fontsource/barlow-semi-condensed/700.css'
import '@fontsource/barlow-semi-condensed/800.css'
import '@fontsource/barlow-semi-condensed/900.css'

import '@fontsource/barlow-semi-condensed/100-italic.css'
import '@fontsource/barlow-semi-condensed/200-italic.css'
import '@fontsource/barlow-semi-condensed/300-italic.css'
import '@fontsource/barlow-semi-condensed/400-italic.css'
import '@fontsource/barlow-semi-condensed/500-italic.css'
import '@fontsource/barlow-semi-condensed/600-italic.css'
import '@fontsource/barlow-semi-condensed/700-italic.css'
import '@fontsource/barlow-semi-condensed/800-italic.css'
import '@fontsource/barlow-semi-condensed/900-italic.css'
