import { TableColumnHeaderProps } from "@chakra-ui/react";

export const ORDER_TABLE_HEADERS: {
    label: string;
    style?: TableColumnHeaderProps;
}[] = [
    { label: "Order ID" },
    { label: "Card Image" },
    { label: "Generated By" },
    { label: "Cost Paid" },
    { label: "Bagtag Quantity" },
    { label: "Physical Card Quantity" },
    { label: "Digital Card Quantity" },
    { label: "Email" },
    { label: "Phone Number", style: { minWidth: "200px" } },
    { label: "Receiver UUID" },
    { label: "Sender UUID" },
    { label: "Shipping First Name" },
    { label: "Shipping Last Name" },
    { label: "Address", style: { minWidth: "200px" } },
    { label: "City" },
    { label: "State" },
    { label: "Zip Code" },
    { label: "Serial Number" },
    { label: "Transaction Type" },
    { label: "Payout Amt" },
    { label: "Sent for Print" },
    { label: "PO Number" },
    { label: "Packaged" },
    { label: "Edit Card" },
    { label: "Download Card Print File" },
    { label: "Download Bag Tag Print File" },
    { label: "View Print File" },
    { label: "Print Shipping Label" },
];
