import React from "react";
import { Table, Thead, Tbody, Tr, Th, Td } from "@chakra-ui/react";
import { orderData } from "./orderData";

interface OrderTableProps {}

export default function OrdersPage({}: OrderTableProps) {
    const thStyles = {
        fontSize: { base: "16px", "2xl": "16px" },
        color: "green.100",
        fontStyle: "italic",
        fontWeight: "semibold",
        fontFamily: "Barlow Condensed",
        w: "full",
        position: "sticky" as const,
        top: 0,
        zIndex: 1,
        background: "gray.800",
    };

    return (
        <Table variant="simple" background="gray.800">
            <Thead>
                <Tr>
                    <Th {...thStyles}>Order ID</Th>
                    <Th {...thStyles}>Card Image</Th>
                    <Th {...thStyles}>Generated By</Th>
                    <Th {...thStyles}>Cost Paid</Th>
                    <Th {...thStyles}>Bagtag Quantity</Th>
                    <Th {...thStyles}>Physical Card Quantity</Th>
                    <Th {...thStyles}>Digital Card Quantity</Th>
                    <Th {...thStyles}>Email</Th>
                    <Th {...thStyles} minWidth="200px">
                        Phone Number
                    </Th>
                    <Th {...thStyles}>Receiver UUID</Th>
                    <Th {...thStyles}>Sender UUID</Th>
                    <Th {...thStyles}>Shipping First Name</Th>
                    <Th {...thStyles}>Shipping Last Name</Th>
                    <Th {...thStyles} minWidth="200px">
                        Address
                    </Th>
                    <Th {...thStyles}>City</Th>
                    <Th {...thStyles}>State</Th>
                    <Th {...thStyles}>Zip Code</Th>
                    <Th {...thStyles}>Serial Number</Th>
                    <Th {...thStyles}>Transaction Type</Th>
                    <Th {...thStyles}>Payout Amt</Th>
                    <Th {...thStyles}>Sent for Print</Th>
                    <Th {...thStyles}>PO Number</Th>
                    <Th {...thStyles}>Packaged</Th>
                    <Th {...thStyles}>Edit Card</Th>
                    <Th {...thStyles}>Download Card Print File</Th>
                    <Th {...thStyles}>Download Bag Tag Print File</Th>
                    <Th {...thStyles}>View Print File</Th>
                    <Th {...thStyles}>Print Shipping Label</Th>
                </Tr>
            </Thead>
            <Tbody>
                {orderData.map((order) => (
                    <Tr key={order.orderId}>
                        <Td>{order.orderId}</Td>
                        <Td>{order.cardImage}</Td>
                        <Td>{order.cardGeneratedBy}</Td>
                        <Td>{order.costPaid}</Td>
                        <Td>{order.bagtagQuantity}</Td>
                        <Td>{order.physicalCardQuantity}</Td>
                        <Td>{order.digitalCardQuantity}</Td>
                        <Td>{order.email}</Td>
                        <Td>{order.phoneNumber}</Td>
                        <Td>{order.receiverUuid}</Td>
                        <Td>{order.senderUuid}</Td>
                        <Td>{order.shippingFirstName}</Td>
                        <Td>{order.shippingLastName}</Td>
                        <Td>{order.address}</Td>
                        <Td>{order.city}</Td>
                        <Td>{order.state}</Td>
                        <Td>{order.zipCode}</Td>
                        <Td>{order.serialNumber}</Td>
                        <Td>{order.transactionType}</Td>
                        <Td>{order.payoutAmt}</Td>
                        <Td>{order.sentForPrint}</Td>
                        <Td>{order.poNumber}</Td>
                        <Td>{order.packaged}</Td>
                        <Td>{order.editCard}</Td>
                        <Td>{order.downloadCardPrintFile}</Td>
                        <Td>{order.downloadBagTagPrintFile}</Td>
                        <Td>{order.printShippingLabel}</Td>
                    </Tr>
                ))}
            </Tbody>
        </Table>
    );
}
