export const orderData = [
    {
        orderId: "12345",
        cardImage: "image_url",
        cardGeneratedBy: "system",
        costPaid: "$100",
        bagtagQuantity: 2,
        physicalCardQuantity: 3,
        digitalCardQuantity: 5,
        email: "example@email.com",
        phoneNumber: "123-456-7890",
        receiverUuid: "receiver_uuid",
        senderUuid: "sender_uuid",
        shippingFirstName: "John",
        shippingLastName: "Doe",
        address: "123 Main St",
        city: "Anytown",
        state: "CA",
        zipCode: "90001",
        serialNumber: "SN123456",
        transactionType: "purchase",
        payoutAmt: "$50",
        sentForPrint: "Yes",
        poNumber: "PO12345",
        packaged: "Yes",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
    {
        orderId: "1001",
        cardImage: "https://example.com/card1.jpg",
        cardGeneratedBy: "System",
        costPaid: "$50",
        bagtagQuantity: 2,
        physicalCardQuantity: 1,
        digitalCardQuantity: 3,
        email: "user1@example.com",
        phoneNumber: "123-456-7890",
        receiverUuid: "UUID_Receiver_1",
        senderUuid: "UUID_Sender_1",
        shippingFirstName: "Alice",
        shippingLastName: "Smith",
        address: "123 Apple St",
        city: "New York",
        state: "NY",
        zipCode: "10001",
        serialNumber: "SN001",
        transactionType: "Purchase",
        payoutAmt: "$25",
        sentForPrint: "Yes",
        poNumber: "PO12345",
        packaged: "No",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
    {
        orderId: "1002",
        cardImage: "https://example.com/card2.jpg",
        cardGeneratedBy: "Admin",
        costPaid: "$75",
        bagtagQuantity: 1,
        physicalCardQuantity: 2,
        digitalCardQuantity: 4,
        email: "user2@example.com",
        phoneNumber: "321-654-0987",
        receiverUuid: "UUID_Receiver_2",
        senderUuid: "UUID_Sender_2",
        shippingFirstName: "Bob",
        shippingLastName: "Johnson",
        address: "456 Orange Ave",
        city: "Los Angeles",
        state: "CA",
        zipCode: "90001",
        serialNumber: "SN002",
        transactionType: "Gift",
        payoutAmt: "$40",
        sentForPrint: "No",
        poNumber: "PO67890",
        packaged: "Yes",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
    {
        orderId: "1003",
        cardImage: "https://example.com/card3.jpg",
        cardGeneratedBy: "System",
        costPaid: "$60",
        bagtagQuantity: 3,
        physicalCardQuantity: 0,
        digitalCardQuantity: 2,
        email: "user3@example.com",
        phoneNumber: "555-123-4567",
        receiverUuid: "UUID_Receiver_3",
        senderUuid: "UUID_Sender_3",
        shippingFirstName: "Charlie",
        shippingLastName: "Brown",
        address: "789 Banana Blvd",
        city: "Chicago",
        state: "IL",
        zipCode: "60601",
        serialNumber: "SN003",
        transactionType: "Purchase",
        payoutAmt: "$30",
        sentForPrint: "Yes",
        poNumber: "PO54321",
        packaged: "No",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
    {
        orderId: "1004",
        cardImage: "https://example.com/card4.jpg",
        cardGeneratedBy: "Admin",
        costPaid: "$90",
        bagtagQuantity: 2,
        physicalCardQuantity: 3,
        digitalCardQuantity: 1,
        email: "user4@example.com",
        phoneNumber: "777-888-9999",
        receiverUuid: "UUID_Receiver_4",
        senderUuid: "UUID_Sender_4",
        shippingFirstName: "David",
        shippingLastName: "Wilson",
        address: "101 Pine St",
        city: "Seattle",
        state: "WA",
        zipCode: "98101",
        serialNumber: "SN004",
        transactionType: "Gift",
        payoutAmt: "$50",
        sentForPrint: "No",
        poNumber: "PO45678",
        packaged: "Yes",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
    {
        orderId: "1005",
        cardImage: "https://example.com/card5.jpg",
        cardGeneratedBy: "System",
        costPaid: "$120",
        bagtagQuantity: 1,
        physicalCardQuantity: 2,
        digitalCardQuantity: 5,
        email: "user5@example.com",
        phoneNumber: "666-555-4444",
        receiverUuid: "UUID_Receiver_5",
        senderUuid: "UUID_Sender_5",
        shippingFirstName: "Emma",
        shippingLastName: "Davis",
        address: "222 Oak St",
        city: "Denver",
        state: "CO",
        zipCode: "80202",
        serialNumber: "SN005",
        transactionType: "Purchase",
        payoutAmt: "$60",
        sentForPrint: "Yes",
        poNumber: "PO98765",
        packaged: "No",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
    {
        orderId: "1006",
        cardImage: "https://example.com/card6.jpg",
        cardGeneratedBy: "User",
        costPaid: "$65",
        bagtagQuantity: 1,
        physicalCardQuantity: 2,
        digitalCardQuantity: 1,
        email: "user6@example.com",
        phoneNumber: "555-000-1234",
        receiverUuid: "UUID_Receiver_6",
        senderUuid: "UUID_Sender_6",
        shippingFirstName: "Sophia",
        shippingLastName: "Miller",
        address: "333 Maple St",
        city: "Austin",
        state: "TX",
        zipCode: "73301",
        serialNumber: "SN006",
        transactionType: "Gift",
        payoutAmt: "$35",
        sentForPrint: "Yes",
        poNumber: "PO65432",
        packaged: "No",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
    {
        orderId: "1007",
        cardImage: "https://example.com/card7.jpg",
        cardGeneratedBy: "Admin",
        costPaid: "$80",
        bagtagQuantity: 2,
        physicalCardQuantity: 1,
        digitalCardQuantity: 3,
        email: "user7@example.com",
        phoneNumber: "444-555-6666",
        receiverUuid: "UUID_Receiver_7",
        senderUuid: "UUID_Sender_7",
        shippingFirstName: "Daniel",
        shippingLastName: "Taylor",
        address: "777 Birch Rd",
        city: "Miami",
        state: "FL",
        zipCode: "33101",
        serialNumber: "SN007",
        transactionType: "Purchase",
        payoutAmt: "$40",
        sentForPrint: "No",
        poNumber: "PO11223",
        packaged: "Yes",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
    {
        orderId: "1008",
        cardImage: "https://example.com/card8.jpg",
        cardGeneratedBy: "System",
        costPaid: "$95",
        bagtagQuantity: 3,
        physicalCardQuantity: 2,
        digitalCardQuantity: 4,
        email: "user8@example.com",
        phoneNumber: "222-333-4444",
        receiverUuid: "UUID_Receiver_8",
        senderUuid: "UUID_Sender_8",
        shippingFirstName: "Olivia",
        shippingLastName: "Anderson",
        address: "555 Cedar Ln",
        city: "San Diego",
        state: "CA",
        zipCode: "92101",
        serialNumber: "SN008",
        transactionType: "Gift",
        payoutAmt: "$45",
        sentForPrint: "Yes",
        poNumber: "PO99887",
        packaged: "No",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
    {
        orderId: "1009",
        cardImage: "https://example.com/card9.jpg",
        cardGeneratedBy: "User",
        costPaid: "$110",
        bagtagQuantity: 2,
        physicalCardQuantity: 3,
        digitalCardQuantity: 2,
        email: "user9@example.com",
        phoneNumber: "777-111-2222",
        receiverUuid: "UUID_Receiver_9",
        senderUuid: "UUID_Sender_9",
        shippingFirstName: "William",
        shippingLastName: "Clark",
        address: "999 Elm St",
        city: "Portland",
        state: "OR",
        zipCode: "97201",
        serialNumber: "SN009",
        transactionType: "Purchase",
        payoutAmt: "$55",
        sentForPrint: "No",
        poNumber: "PO33445",
        packaged: "Yes",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
    {
        orderId: "1010",
        cardImage: "https://example.com/card10.jpg",
        cardGeneratedBy: "Admin",
        costPaid: "$125",
        bagtagQuantity: 1,
        physicalCardQuantity: 4,
        digitalCardQuantity: 5,
        email: "user10@example.com",
        phoneNumber: "888-999-0000",
        receiverUuid: "UUID_Receiver_10",
        senderUuid: "UUID_Sender_10",
        shippingFirstName: "Lucas",
        shippingLastName: "White",
        address: "222 Pine Ln",
        city: "Boston",
        state: "MA",
        zipCode: "02108",
        serialNumber: "SN010",
        transactionType: "Gift",
        payoutAmt: "$60",
        sentForPrint: "Yes",
        poNumber: "PO55667",
        packaged: "No",
        editCard: "Edit",
        downloadCardPrintFile: "Download",
        downloadBagTagPrintFile: "Download",
        printShippingLabel: "Print",
    },
];

{
    /* <Text

>
{item.title}
</Text>
{item.subtitles && (
<SharedStack>
    {item.subtitles.map((subtitle) => (
        <Text
            w="full"
            key={subtitle}
            fontSize={{ base: "16px", "2xl": "36px" }}
            color="white"
            fontStyle="italic"
            fontWeight={{
                base: "medium",
                "2xl": "semibold",
            }}
            fontFamily="Barlow Condensed"
        >
            • {subtitle}
        </Text> */
}
