/* eslint-disable func-style */
import { Handler, APIGatewayProxyEvent, APIGatewayProxyResult } from "aws-lambda";
import { DynamoDB } from "aws-sdk";
import { sendResponse } from "../utils/responseFunctions";
import { dbTables } from "../../EnvironmentManager/EnvironmentManager";

// Create an instance of the DynamoDB DocumentClient
const dynamoDb = new DynamoDB.DocumentClient();

/**
 * Gets pre-existing cards based off the user's uuid
 * @param event - The API Gateway event object.
 * @returns A promise that resolves to the API Gateway proxy result.
 */
export const getCreatedCards: Handler = async(event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> => {

	try {
		if (event.body) {
			const body = JSON.parse(event.body || "");
			const { generatedBy } = body;

			// Check to see if the request body contains a uuid and generatedBy value
			if (!generatedBy) {
				return sendResponse(400, { error: "The request body requires a generatedBy value" });
			}

			// Define the parameters for the DynamoDB get operation
			const params = {
				TableName: dbTables.GamechangersCards(),
				KeyConditionExpression: "generatedBy = :generatedBy",
				ExpressionAttributeValues: {
					":generatedBy": generatedBy,
				},
			};

			// Retrieve the card item from the DynamoDB table
			const data = await dynamoDb.query(params).promise();

			// Check if the card item exists
			if (!data.Items) {
				return sendResponse(404, { error: "The cards generated by this user do not exist" });
			}

			// Sort the card items by createdAt attribute, assuming 0 if missing
			const sortedItems = data.Items.sort((a, b) => {
				const createdAtA = a.createdAt || 0;
				const createdAtB = b.createdAt || 0;
				return createdAtB - createdAtA;
			});

			return sendResponse(200, sortedItems as object[]);

		}

		// Return an error response with a 400 status code if the request body is empty
		return sendResponse(400, { error: "The request body cannot be empty" });

	} catch (error) {
		// Log the error if an exception occurs
		console.error("The following error occurred when retrieving a card: ");
		console.error(error);

		// Return an error response with a 500 status code
		return sendResponse(500, { error: "An error occurred when retrieving the card" });
	}
};
