/* eslint-disable max-len */

/**
 * Constants for FAQ page accordion component
 */
export default class FAQConstants {

	static FAQ_DATA = {
		THE_PLATFORM: [
			{
				title: "What is OnFire Athletes?",
				content: "OnFire Athletes is a first-of-its-kind platform that allows athletes to capture, create, and customize their own digital and physical 3D Augmented Reality (AR) sports cards. These cards can be traded, sold, and used to showcase their most memorable sports moments."
			},
			{
				title: "What sets OnFire Athletes apart?",
				content: "OnFire Athletes introduces a new era of sports cards by combining 3D design with Augmented Reality (AR) interactivity. These cards bridge the gap between physical and digital formats, offering a dynamic and engaging experience unlike anything else. The platform empowers athletes of all ages, backgrounds, locations, and sports to create their own customizable cards on their terms. Athletes can trade their cards with friends, family, and fans or monetize their Name, Image, and Likeness (NIL) by selling them in the Locker Room marketplace."
			},
			{
				title: "How do I create a card?",
				content: "To create a card, simply visit the “Create” page on our website, where our intuitive card creator will guide you through the process step by step. For the best results, we recommend using high-resolution photos and videos."
			},
			{
				title: "What are the costs?",
				content: "OnFire Athletes offers three packages, each with optional add-ons. Detailed pricing information can be found after you create your OnFire Athletes card."
			},
			{
				title: "How can I sell my digital card?",
				content: "To sell your digital card, select the All-Star package during the card creation process. This package grants access to sell your card in the Locker Room marketplace."
			},
			{
				title: "How can I earn money with my card?",
				content: "Athletes who choose the All-Star package can sell their cards in the Locker Room marketplace with a minimum selling price of $20. Athletes receive 80%* of each sale. Additionally, every digital card purchase in the Locker Room marketplace includes a physical 3D (AR) card. To maximize your sales, leverage your social media presence, network, and community."
			},
			{
				title: "How can people purchase my card?",
				content: "Anyone can purchase your card through the Locker Room marketplace."
			},
			{
				title: "How can I withdraw my sales proceeds?",
				content: "Athletes can withdraw their earnings via a verified Stripe account. Setting up a Stripe account is free of charge."
			},
			{
				title: "How do I purchase cards on the platform?",
				content: "Visit the Locker Room marketplace or an athlete’s profile, select the card you want, and click “Buy Now” to complete your purchase. Payments can be made using any major credit card or Game Coin (GMEX) tokens. Purchases made with GMEX tokens receive a 20% discount. The purchased card will appear in your profile under the “Bought” album."
			},
			{
				title: "How do I trade cards on the platform?",
				content: "Visit the Locker Room marketplace or an athlete’s profile, select the card you want, and click “Request Trade” to initiate the process. Once the trade is confirmed, the card will appear in your profile under the “Traded” album."
			}
		],
		GMEX: [
			{
				title: "What is Game Coin (GMEX)?",
				content: "Game Coin (GMEX) is the utility token for the OnFire Athletes platform. When you use GMEX tokens for purchases, you receive a 20% discount on the price. Learn more about GMEX at thegamecoin.net."
			},
			{
				title: "How do I purchase Game Coin (GMEX)?",
				content: "GMEX tokens can be purchased on PancakeSwap or BitMart."
			},
			{
				title: "How do I use Game Coin (GMEX) to make purchases on the OnFire Athletes platform?",
				content: "At checkout, select Game Coin (GMEX) as your payment method to complete your purchase using GMEX tokens. If you’re using an Apple device, please use a compatible browser, such as Chrome, as Safari does not support the GMEX checkout process."
			},
		],
		LEGAL: [
			{
				title: "Terms of Use",
				content:[
					"Last Modified: August 16, 2024",
					"This document contains important information regarding your rights and obligations, please read it carefully.",
					"OnFire Athletes, LLC (\"OnFire Athletes\", \"we\", or \"us\") hosts a web-based platform that provides users with the opportunity to create, sell, purchase, collect, trade and showcase digital Sports Cards (collectively, the “Platform”). OnFire Athletes is making the Platform available to you. However, before you use the Platform, you will need to agree to these Terms of Use and any terms and conditions incorporated herein by reference (collectively, these “Terms\").",
					"PLEASE READ THESE TERMS CAREFULLY BEFORE USING THE PLATFORM. THESE TERMS GOVERN YOUR USE OF THE PLATFORM, UNLESS WE HAVE EXECUTED A SEPARATE WRITTEN AGREEMENT WITH YOU FOR THAT PURPOSE. WE ARE ONLY WILLING TO MAKE THE PLATFORM AVAILABLE TO YOU IF YOU ACCEPT ALL OF THESE TERMS. BY USING THE PLATFORM OR ANY PART OF IT, OR BY CLICKING “I ACCEPT” BELOW OR INDICATING YOUR ACCEPTANCE IN AN ADJOINING BOX, YOU ARE CONFIRMING THAT YOU UNDERSTAND AND AGREE TO BE BOUND BY ALL OF THESE TERMS.",
					"IF YOU ARE ACCEPTING THESE TERMS ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE LEGAL AUTHORITY TO ACCEPT THESE TERMS ON THAT ENTITY’S BEHALF, IN WHICH CASE “YOU” WILL MEAN THAT ENTITY. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT ACCEPT ALL OF THESE TERMS, THEN WE ARE UNWILLING TO MAKE THE PLATFORM AVAILABLE TO YOU. IF YOU DO NOT AGREE TO THESE TERMS, YOU MAY NOT ACCESS OR USE THE PLATFORM.",
					"THIS AGREEMENT CONTAINS AN ARBITRATION PROVISION. PLEASE REVIEW THE ARBITRATION PROVISION CAREFULLY, SINCE IT AFFECTS YOUR LEGAL RIGHTS. BY USING THE PLATFORM OR ANY PART OF IT, OR BY CLICKING “I ACCEPT” BELOW OR INDICATING YOUR ACCEPTANCE IN AN ADJOINING BOX, YOU UNDERSTAND AND AGREE TO BE BOUND BY THE ARBITRATION PROVISION.",
					"ANY PURCHASE OR SALE YOU MAKE, ACCEPT OR FACILITATE OUTSIDE OF THIS PLATFORM OF A DIGITAL SPORTS CARD WILL BE ENTIRELY AT YOUR RISK.",
					"These Terms of Use are effective as of the date first written above. We reserve the right to change these Terms of Use from time to time without notice to you. You acknowledge and agree that it is your responsibility to review these Terms of Use periodically and to be aware of any modifications. Your continued use of this site after such modifications will constitute your acknowledgement of the modified Terms of Use and agreement to abide and be bound by the modified Terms of Use.",
					"You may not use this Platform if you: (i) do not agree to these Terms; (ii) are below the age of thirteen; or (iii) are prohibited from accessing or using this Platform or any of this Platform’s contents, products, or services by applicable law.",
					"As used in these Terms of Use, references to our “Affiliates” include our owners, subsidiaries, affiliated companies, officers, directors, suppliers, partners, sponsors, and advertisers, and includes (without limitation) all parties involved in creating, producing, and/or delivering this site and/or its contents.",
					"1. USE OF THE PLATFORM; ACCOUNT SET-UP AND SECURITY",
					"(i) Account Registration. To use the platform, we require that you create a user account by completing our online registration form, which requests certain information and data about yourself (“Registration Data”). By registering, you agree that all information provided in the Registration Data is true and accurate and that you will maintain and update this information as required to keep it current, complete and accurate. You may delete your account at any time. However, by deleting your account, you are agreeing to the deletion of all digital Sports Cards created or held in your Locker Room.",
					"(ii) You grant us the right to disclose to third parties certain Registration Data about you. The information we obtain through your use of this Platform, including your Registration Data, is subject to our Privacy Policy, which is specifically incorporated by reference into these Terms of Use.",
					"(iii) We reserve the sole right to either modify or discontinue the platform, including any features therein, at any time with or without notice to you. We shall not be liable to you, or any third party should we exercise such a right. Modifications may include, but are not limited to, changes in the pricing structure, the addition of fee-based services, or changes to limitations on allowable file sizes. Any new features that augment or enhance the then- current services on this site shall also be subject to these Terms of Use.",
					"(iv) You understand and agree that temporary service interruptions may occur as normal events.",
					"(v) You understand and agree that we have no control over third party networks you may access during your use of this Platform, and therefore, delays and disruption of other network transmissions are completely beyond our control.",
					"(vi) You are responsible for the security of your account and for the security of any connected credit card or electronic wallet. If you become aware of any unauthorized use of your password or of your account with us, you agree to notify us immediately at support@Getinthegame.net",
					"(vii) If you use a service on this platform that requires payment of a fee, you agree to pay all fees associated with the service. Charges for services can be paid with an approved credit card or with GameCoin/GMEX (“GMEX”) cryptocurrency utilizing a supported electronic wallet. Purchasers using GMEX receive a 20% discount.",
					"(viii) Purchases made using a credit card are processed by a third party, such as Stripe, Inc. Purchases made using GMEX are processed by a third party via aconnected digital wallet. You understand that your digital wallet address willbe made publicly visible whenever you engage in a transaction on the Platform and pay with cryptocurrency. We have no control over these transactions, nor do we have the ability to reverse any transactions. We have no liability to you or to any third party for any claims or damages that may arise as a result of any transaction that you engage in using your credit card or connected digital wallet. We do not provide refunds for any purchases that you might make on or through the platform.",
					"(ix) You will be solely responsible to pay any and all sales, use, value-added and other taxes, duties, and assessments (except taxes on our net income) now or hereafter claimed or imposed by any governmental authority (collectively, the “Taxes”) associated with your use of the Platform. Except for income taxes levied on us, you: (a) will pay or reimburse us for all national, federal, state, local or other taxes and assessments of any jurisdiction, including value added taxes and taxes as required by international tax treaties, customs or other import or export taxes, and amounts levied in lieu thereof based on charges set, services performed or payments made hereunder, as are now or hereafter may be imposed under the authority of any national, state, local or any other taxing jurisdiction; and (b) will not be entitled to deduct the amount of any such taxes, duties or assessments from payments (including Fees) made to us pursuant to these Terms.",
					"2. DIGITAL SPORTS CARDS",
					"Digital Sports Cards are created by uploading your photograph, signature, a short video, certain biographical information and information about your team. When you create a Digital Sports Card, you can also purchase a physical sports card (“Augmented Reality Card”) that can display your Digital Sports Card using your smartphone. Digital Sports Cards you create or acquire by trade or purchase are displayed in your profile. Digital Sports Cards can be sold or traded to anyone who has an approved user account. However, to be paid as the seller, you must have a verified payment account.",
					"Periodically, you will be able to earn Digital Sports Cards for free by participating in certain marketing campaigns on the Platform, partnering in a campaign or by completing certain in-Platform requirements, that we may offer from time to time.",
					"3. TRANSACTION FEES",
					"From the sale of each Digital Sports Card you create, OnFire Athletes will receive a transaction fee in the amount of 20%, from the payment processor, calculated on the Net Sales. Net Sales, when paying with a credit card, are defined as Gross Sales less (i) any credit card processing fees and (2) the cost of your Augmented Reality Card. Net Sales, when paying GMEX are defined as Gross Sales less (i) 20% and (2) the cost of your Augmented Reality Card.",
					"4. OWNERSHIP, LICENSE, AND OWNERSHIP RESTRICTIONS",
					"For the purposes of this Section 4, the following capitalized terms will have the following meanings:",
					"(1) “Our Art” means and includes any art, design, drawing, templet or feature we furnish or make available to users on the Platform.",
					"(2) “Your Art” means and includes any art, design, drawing, photograph, video, biographical information, signature or team information you upload to the Platform.",
					"(3) “Third Party IP” means and includes any intellectual property rights, patent rights, copyrights, trade secrets, trademarks and service marks owned by someone other than you or Us.",
					"(i) Because each Digital Sports Card you create consists of a combination of Our Art, Your Art and Third-Party IP, neither you nor we own them. Notwithstanding, we agree that you shall have a non-exclusive transferable license to use and display Our Art, and Third-Party IP, solely in connection with Your Art, for the purpose of creating and displaying, and allowing others to display Digital Sports Cards you create in accordance with these Terms (and not through any of the Category B Prohibited Activities",
					"(ii) We Own the Platform. You acknowledge and agree that we (or, as applicable, our licensors) owns all legal right, title and interest in and to all other elements of the Platform, and all intellectual property rights therein (including, without limitation, all Art, designs, systems, methods, information, computer code, software, services, “look and feel”, organization, compilation of the content, code, data, and all other elements of the Platform (collectively, the “Platform Materials”)). You acknowledge that Platform Materials are protected by copyright, trade dress, patent, and trademark laws, international conventions, other relevant intellectual property and proprietary rights, and applicable laws. All Platform Materials are the copyrighted property of us or our licensors, and all trademarks, service marks, and trade names associated with the Platform or otherwise contained in the Platform Materials are proprietary to us or our licensors.",
					"(iii) No User License or Ownership of Platform Materials. Except as expressly set forth herein, your use of the Platform does not grant you ownership of or any other rights with respect to any content, code, data, or other Platform Materials that you may access on or through the Platform. We reserve all rights in and to the Platform Materials that are not expressly granted to you in these Terms.",
					"(iv) Further User Ownership Acknowledgements. For the sake of clarity, you understand and agree: (a) that your purchase of a Digital Sports Card, whether via the Platform or otherwise, does not give you any rights or licenses in or to the Platform Materials (including, without limitation, our copyright in and to Our Art) other than those expressly contained in these Terms; (b) that you do not have the right, except as otherwise set forth in these Terms, to reproduce, distribute, or otherwise commercialize any elements of the Platform Materials (including, without limitation, Our Art) without our prior written consent in each case, which consent we may withhold in our sole and absolute discretion; and (c) that you will not apply for, register, or otherwise use or attempt to use any of our trademarks or service marks, or any confusingly similar marks, anywhere in the world without our prior written consent in each case, which consent we may withhold at our sole and absolute discretion.",
					"(vi) Restrictions on Ownership. You agree that you may not, nor permit any third party to do or attempt to do any of the following without our (or, as applicable, our licensors’) express prior written consent in each case: (a) modify Our Art in any way, including, without limitation, the shapes, designs, drawings, attributes, or color schemes, (b) use Our Art to advertise, market, or sell any third party product or service; (c) use Our Art in connection with images, videos, or other forms of media that depict hatred, intolerance, violence, cruelty, or anything else that could reasonably be found to constitute hate speech or otherwise infringe upon the rights of others; (d) use Our Art in movies, videos, or any other forms of media, except to the limited extent that such use is expressly permitted in these Terms; (e) sell, distribute for commercial gain (including, without limitation, giving away in the hopes of eventual commercial gain), or otherwise commercialize merchandise that includes, contains, or consists of Our Art; (f) attempt to trademark, copyright, or otherwise acquire additional intellectual property rights in or to Our Art; or (g) otherwise utilize Our Art for any intended activity not expressly permitted in these Terms.",
					"(vii) Third-Party IP. Your Art may not contain any unlicensed Third-Party IP. If we are made aware of a claim that Your Art contains unlicensed Third-Party IP (e.g., unlicensed intellectual property from your high school, state sports association, college, or NCAA), you will be promptly notified that your digital Sports Card has been removed from our platform in accordance with the provisions of the Digital Millennium Copyright Act, which shall control. You relieve and release us from any liability for the good-faith removal or disabling of access to material claimed to be infringing as the result of a compliant takedown notice—even if the material is not ultimately found to be infringing. You understand and agree: (a) that you do not have the right to use unapproved Third Party IP in any way, (b) that, depending on the nature of the license being infringed upon from the owner of the Third Party IP, we may need to (and reserve every right to) pass through additional restrictions on your ability to use the Platform; and (c) to the extent that we inform you of such additional restrictions in writing, you will be responsible for complying with all such restrictions from the date that you receive the notice, and that failure to do so will be deemed a breach of the license contained in this Section 4.",
					"(viii) Other Terms of License.",
					"(ix) User Feedback. You may choose to submit comments, bug reports, ideas or other feedback about the Platform, including without limitation about how to improve the Platform (collectively, “Feedback”). By submitting any Feedback, you agree that we are free to use such Feedback at our discretion and without additional compensation to you, and to disclose such Feedback to third parties (whether on a non-confidential basis, or otherwise). You hereby grant us a perpetual, irrevocable, nonexclusive, worldwide license under all rights necessary for us to incorporate and use your Feedback for any purpose.",
					"(x) By creating a Digital Sports Card, you grant to OnFire Athletes a worldwide, non-exclusive, royalty-free, sublicensable and transferable license to use Your Art in connection with the Platform and our Digital Sports Card’s (and its successors' and affiliates') business, including for the purpose of marketing part or all of the Platform and its services.",
					"5. CONDITIONS OF USE AND PROHIBITED ACTIVITIES YOU AGREE THAT YOU ARE RESPONSIBLE FOR YOUR OWN CONDUCT WHILE ACCESSING OR USING THE PLATFORM, AND FOR ANY CONSEQUENCES THEREOF. YOU AGREE TO USE THE PLATFORM ONLY FOR PURPOSES THAT ARE LEGAL, PROPER AND IN ACCORDANCE WITH THESE TERMS AND ANY APPLICABLE LAWS OR REGULATIONS.",
					"(i) User Warranties. Without limiting the foregoing, you warrant and agree that your use of the Platform will not (and will not allow any third party to):",
					"(a) in any manner:",
					"(1) involve the sending, uploading, distributing or disseminating any unlawful, defamatory, harassing, abusive, fraudulent, obscene, or otherwise objectionable content;",
					"(2) involve the distribution of any viruses, worms, defects, Trojan horses, corrupted files, hoaxes, or any other items of a destructive or deceptive nature.",
					"(3) involves the uploading, posting, transmitting or otherwise making available through the Platform any content that infringes the intellectual proprietary rights of any person.",
					"(4) involve using the Platform to violate the legal rights (such as rights of privacy and publicity) of others.",
					"(5) involve engaging in, promoting, or encouraging illegal activity.",
					"(6) involve interfering with other users’ enjoyment of the Platform.",
					"(7) involve exploiting the Platform for any unauthorized commercial purpose.",
					"(8) involve modifying, adapting, translating, or reverse engineering any portion of the Platform.",
					"(9) involve removing any copyright, trademark or other proprietary rights notices contained in or on the Platform or any part of it.",
					"(10) involve reformatting or reconfiguring any portion of the Platform.",
					"(11) involve displaying any content on the Platform that contains any hate- related or violent content or contains any other material, products or services that violate or encourage conduct that would violate any criminal laws, any other applicable laws, or any third-party rights.",
					"(12) involve using any spider, site search/retrieval application, or other device to retrieve or index any portion of the Platform or the content posted on the Platform, or to collect information about its users for any unauthorized purpose.",
					"(13) involve accessing or using the Platform for the purpose of creating a product or service that is competitive with any of our products or services.",
					"(14) involve abusing, harassing, or threatening another user of the Platform or any of our authorized representatives, customer service personnel, chat board moderators, or volunteers (including, without limitation, filing support tickets with false information, sending excessive emails or support tickets, obstructing our employees from doing their jobs, refusing to follow the instructions of our employees, or publicly disparaging us by implying favoritism by one of our employees or otherwise); or",
					"(15) involve using any abusive, defamatory, ethnically or racially offensive, harassing, harmful, hateful, obscene, offensive, sexually explicit, threatening or vulgar language when communicating with another user of the Platform or any of our authorized representatives, customer service personnel, chat board moderators, or volunteers (each, a “Category A Prohibited Activity”); and/or",
					"(b) in any manner:",
					"(1) involve creating user accounts by automated means or under false or fraudulent pretenses.",
					"(2) involve the impersonation of another person (via the use of an email address or otherwise).",
					"(3) involve using, employing, operating, or creating a computer program to simulate the human behavior of a user (“Bots”).",
					"(4) involve using, employing, or operating Bots or other similar forms of automation to engage in any activity or transaction on the Platform (including, without limitation, creation of Digital Sports Cards and purchases of Digital Sports Cards on the Marketplace).",
					"(5) involve acquiring Digital Sports Cards through inappropriate or illegal means (including, among other things, using a stolen credit card, or a payment mechanism that you do not have the right to use, or purchasing a Digital Sports Card and then attempting to charge the cost back to your payment method while still maintaining ownership or control of the Digital Sports Card or selling, gifting or trading the Digital Sports Card to someone else); or",
					"(6) involve the purchasing, selling or facilitating the purchase and sale of any user’s account(s) to other users or third parties for cash or cryptocurrency consideration outside of the Platform; or",
					"(7) otherwise involve or result in the wrongful seizure or receipt of any Digital Sports Cards or other digital assets (each, a “Category B Prohibited Activity” and, together with Category A Prohibited Activity, the “Prohibited Activities”).",
					"(ii) Effect of Your Breaches. If you engage in any of the Prohibited Activities, we may, at our sole and absolute discretion, without notice or liability to you, and without limiting any of our other rights or remedies at law or in equity, immediately suspend or terminate your user account and/or delete your Digital Sports Cards’ images and descriptions from the Platform.",
					"NOTWITHSTANDING THE FOREGOING, HOWEVER, IF WE REASONABLY BELIEVE THAT YOU ARE ENGAGED IN ANY OF THE CATEGORY B PROHIBITED ACTIVITIES, IN ADDITION TO OUR RIGHT TO IMMEDIATELY SUSPEND OR TERMINATE YOUR USER ACCOUNT AND/OR DELETE YOUR DIGITAL SPORTS CARDS’ IMAGES AND DESCRIPTIONS FROM THE PLATFORM, WE ALSO RESERVE THE RIGHT, AT OUR SOLE AND ABSOLUTE DISCRETION, WITHOUT NOTICE OR LIABILITY TO YOU, TO TAKE ANY OR ALL OF THE FOLLOWING ACTIONS: (A) TO DEEM ANY TRANSACTION THAT TOOK PLACE VIA OR AS THE RESULT OF SUCH ACTIVITIES TO BE VOID AB INITIO; AND/OR (B) TO IMMEDIATELY CONFISCATE ANY DIGITAL SPORTS CARDS THAT WERE PURCHASED OR ACQUIRED AS THE RESULT OF SUCH ACTIVITIES.",
					"6. TERMINATION",
					"(i) You May Terminate. If you cancel your account, or otherwise terminate these Terms, you will not receive any refunds for any purchases that you might make on or through the Platform – whether for Digital Sports Cards or anything else.",
					"(ii) We May Terminate. You agree that we, in our sole discretion and for any or no reason, may terminate these Terms and suspend and/or terminate your account(s) for the Platform without the provision of prior notice. You agree that any suspension or termination of your access to the Platform may be without prior notice, and that we will not be liable to you or to any third party for any such suspension or termination.",
					"(iii) Other Remedies Available. If we terminate these Terms or suspend or terminate your access to or use of the Platform due to your breach of these Terms or any suspected fraudulent, abusive, or illegal activity (including, without limitation, if you engage in any of the Prohibited Activities), then termination of these Terms will be in addition to any other remedies we may have at law or in equity.",
					"(iv) Referral to Governmental Authority. We have the right, without provision of prior notice, to take appropriate legal action, including, without limitation, referral to law enforcement or regulatory authority, or notifying the harmed party of any illegal or unauthorized use of the Platform. Without limiting the foregoing, we have the right to fully cooperate with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone using the Platform.",
					"(v) Effect of Termination. Upon any termination or expiration of these Terms, whether by you or us, you may no longer have access to information that you have posted on the Platform or that is related to your account, and you acknowledge that we will have no obligation to maintain any such information in our databases or to forward any such information to you or to any third party. Sections 1 and 3 through 17 will survive the termination or expiration of these Terms for any reason.",
					"YOU WAIVE AND HOLD US AND OUR PARENT, SUBSIDIARIES, AFFILIATES AND OUR AND THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS, AND SUCCESSORS HARMLESS FROM ANY AND ALL CLAIMS RESULTING FROM ANY ACTION TAKEN BY US AND ANY OF THE FOREGOING PARTIES RELATING TO ANY INVESTIGATIONS BY EITHER US OR SUCH PARTIES OR BY LAW ENFORCEMENT AUTHORITIES.",
					"7. DISCLAIMERS YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR ACCESS TO AND USE OF THE PLATFORM IS AT YOUR SOLE RISK, AND THAT THE PLATFORM IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE, OUR SUBSIDIARIES, AFFILIATES, AND LICENSORS MAKE NO EXPRESS WARRANTIES AND HEREBY DISCLAIM ALL IMPLIED WARRANTIES REGARDING THE PLATFORM AND ANY PART OF IT, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, CORRECTNESS, ACCURACY, OR RELIABILITY. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, WE, OUR PARENT, SUBSIDIARIES, AFFILIATES, AND LICENSORS DO NOT REPRESENT OR WARRANT TO YOU THAT: (I) YOUR ACCESS TO OR USE OF THE PLATFORM WILL MEET YOUR REQUIREMENTS; (II) YOUR ACCESS TO OR USE OF THE PLATFORM WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR; (III) USAGE DATA PROVIDED THROUGH THE PLATFORM WILL BE ACCURATE; (IV) THE PLATFORM OR ANY CONTENT, SERVICES, OR FEATURES MADE AVAILABLE ON OR THROUGH THE PLATFORM ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (V) THAT ANY DATA THAT YOU DISCLOSE WHEN YOU USE THE PLATFORM WILL BE SECURE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.",
					"YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET AND AGREE THAT WE HAVE NO LIABILITY OR RESPONSIBILITY FOR ANY BREACH OF SECURITY UNLESS IT IS DUE TO OUR GROSS NEGLIGENCE.",
					"WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSSES YOU INCUR AS THE RESULT OF YOUR USE OF ANY ASSOCIATED PUBLIC BLOCKCHAIN NETWORK, OR YOUR ELECTRONIC WALLET, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS ARISING FROM: (I) USER ERROR, SUCH AS FORGOTTEN PASSWORDS OR INCORRECTLY CONSTRUED SMART CONTRACTS OR OTHER TRANSACTIONS; (II) SERVER FAILURE OR DATA LOSS; (III) CORRUPTED WALLET FILES; OR (IV) UNAUTHORIZED ACCESS OR ACTIVITIES BY THIRD PARTIES, INCLUDING, BUT NOT LIMITED TO, THE USE OF VIRUSES, PHISHING, BRUTE-FORCING OR OTHER MEANS OF ATTACK AGAINST THE PLATFORM, ANY ASSOCIATED PUBLIC BLOCKCHAIN NETWORK, OR ANY ELECTRONIC WALLET.",
					"8. LIMITATION OF LIABILITY",
					"YOU UNDERSTAND AND AGREE THAT WE, OUR PARENT, SUBSIDIARIES, AFFILIATES AND LICENSORS WILL NOT BE LIABLE TO YOU OR TO ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES WHICH YOU MAY INCUR, HOWSOEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, INCLUDING, WITHOUT LIMITATION, ANY LOSS OF PROFITS (WHETHER INCURRED DIRECTLY OR INDIRECTLY), LOSS OF GOODWILL OR BUSINESS REPUTATION, LOSS OF DATA, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, DIMINUTION OF VALUE OR ANY OTHER INTANGIBLE LOSS, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.",
					"YOU AGREE THAT OUR TOTAL, AGGREGATE LIABILITY TO YOU FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR ACCESS TO OR USE OF (OR YOUR INABILITY TO ACCESS OR USE) ANY PORTION OF THE PLATFORM, WHETHER IN CONTRACT, TORT, STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, IS LIMITED TO THE GREATER OF THE AMOUNTS YOU HAVE ACTUALLY AND LAWFULLY PAID US UNDER THESE TERMS IN THE TWO (2) MONTH PERIOD PRECEDING THE DATE THE CLAIM AROSE. YOU ACKNOWLEDGE AND AGREE THAT WE HAVE MADE THE PLATFORM AVAILABLE TO YOU AND ENTERED INTO THESE TERMS IN RELIANCE UPON THE REPRESENTATIONS AND WARRANTIES, DISCLAIMERS AND LIMITATIONS OF LIABILITY SET FORTH HEREIN, WHICH REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN US AND YOU AND FORM AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN US AND YOU. WE WOULD NOT BE ABLE TO PROVIDE THE PLATFORM TO YOU WITHOUT THESE LIMITATIONS.",
					"9. ASSUMPTION OF RISK",
					"(i) Value and Volatility. The prices of collectible blockchain assets are extremely volatile and subjective and collectible blockchain assets have no inherent or intrinsic value. Fluctuations in the price of other digital assets could materially and adversely affect the value of your Digital Sports Cards, which may also be subject to significant price volatility. Each Digital Sports Card has no inherent or intrinsic value. We cannot guarantee that any Digital Sports Cards purchased will retain their original value, as the value of collectibles is inherently subjective and factors occurring outside of the Digital Sports Card’s ecosystem may materially impact the value and desirability of any particular Digital Sports Card. (ii) Tax Calculations. You are solely responsible for determining what, if any, taxes apply to your Digital Sports Card-related transactions. We are not responsible for determining the taxes that apply to your transactions on the Platform. (iii) Inherent Risks with Internet Currency. There are risks associated with using an Internet-based currency, including, but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your electronic wallet. You accept and acknowledge that we will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using our supporting blockchain network, however caused. (v) Regulatory Uncertainty. The regulatory regime governing blockchain technologies, cryptocurrencies and tokens is uncertain, and new regulations or policies may materially adversely affect the development of the Digital Sports Card ecosystem, and therefore the potential utility or value of your Digital Sports Cards.",
					"10. INDEMNIFICATION",
					"You agree to hold harmless and indemnify us and our parent, subsidiaries, affiliates, officers, agents, employees, advertisers, licensors, suppliers or partners from and against any claim, liability, loss, damage (actual and consequential) of any kind or nature, suit, judgment, litigation cost and attorneys' fees arising out of or in any way related to: (i) your breach of these Terms; (ii) your misuse of the Platform; or (iii) your violation of applicable laws, rules or regulations in connection with your access to or use of the Platform. You agree that we will have control of the defense or settlement of any such claims.",
					"11. EXTERNAL SITES",
					"The Platform may include hyperlinks to other websites or resources (collectively, the “External Sites”), which are provided solely as a convenience to our users. We have no control over any External Sites. You acknowledge and agree that we are not responsible for the availability of any External Sites, and that we do not endorse any advertising, products or other materials on or made available from or through any External Sites. Furthermore, you acknowledge and agree that we are not liable for any loss or damage which may be incurred as a result of the availability or unavailability of the External Sites, or as a result of any reliance placed by you upon the completeness, accuracy or existence of any advertising, products or other materials on, or made available from, any External Sites.",
					"12. FORCE MAJEURE",
					"(i) Force Majeure Events. We will not be liable or responsible to the you, nor be deemed to have defaulted under or breached these Terms, for any failure or delay in fulfilling or performing any of these Terms, when and to the extent such failure or delay is caused by or results from the following force majeure events (“Force Majeure Event(s)”): (a) acts of God; (b) flood, fire, earthquake, epidemics, pandemics, including the 2019 novel coronavirus pandemic (COVID-19), tsunami, explosion; (c) war, invasion, hostilities (whether war is declared or not), terrorist threats or acts, riot or other civil unrest; (d) government order, law, or action; (e) embargoes or blockades in effect on or after the date of this agreement; (f) strikes, labor stoppages or slowdowns or other industrial disturbances; (g) shortage of adequate or suitable Internet connectivity, telecommunication breakdown or shortage of adequate power or electricity; and (h) other similar events beyond our control. (ii) Performance During Force Majeure Events. If we suffer a Force Majeure Event, we will use reasonable efforts to promptly notify you of the Force Majeure Event, stating the period of time the occurrence is expected to continue. We will use diligent efforts to end the failure or delay and ensure the effects of such Force Majeure Event are minimized. We will resume the performance of our obligations as soon as reasonably practicable after the removal of the cause. In the event that our failure or delay remains uncured for a period of forty-five (45) consecutive days following written notice given by us under this Section 12, we may thereafter terminate these Terms upon fifteen (15) days' written notice.",
					"13. CHANGES TO THE PLATFORM",
					"We are constantly innovating the Platform to help provide the best possible experience. You acknowledge and agree that the form and nature of the Platform, and any part of it, may change from time to time without prior notice to you, and that we may add new features and change any part of the Platform at any time without notice.",
					"14. CHILDREN",
					"We require all users to be 13 years old or older. If you are under thirteen, you may use a parent or guardian's account, but only with involvement of the account holder. However, the account holder is responsible for everything done with that account.",
					"15. PRIVACY POLICY",
					"Our Privacy Policy describes the ways we collect, use, store and disclose your personal information, and is hereby incorporated by this reference into these Terms. You agree to the collection, use, storage, and disclosure of your data in accordance with our Privacy Policy.",
					"Any communication or material that you transmit to this site or to us, whether by electronic mail or other means, for any reason, will be treated as nonconfidential and nonproprietary. While you retain all rights in such communications or material, you grant us and our designated licensees a nonexclusive, paid-up, perpetual, and worldwide right to copy, distribute, display, perform, publish, translate, adapt, modify, and otherwise use such material for any purpose regardless of the form or medium (now known or not currently known) in which it is used.",
					"Please do not submit confidential or proprietary information to us unless we have mutually agreed in writing otherwise. We are also unable to accept your unsolicited ideas or proposals, so please do not submit them to us in any circumstance.",
					"16. DISPUTE RESOLUTION; BINDING ARBITRATION YOU ARE AGREEING TO GIVE UP ANY RIGHTS TO LITIGATE CLAIMS IN A COURT OF LAW. OTHER RIGHTS THAT YOU WOULD HAVE IF YOU WENT TO COURT MAY ALSO BE UNAVAILABLE OR MAY BE LIMITED IN ARBITRATION. YOU HEREBY EXPRESSLY GIVE UP YOUR RIGHT TO HAVE A TRIAL BY JURY. YOU HEREBY EXPRESSLY GIVE UP YOUR RIGHT TO PARTICIPATE AS A MEMBER OF A CLASS OF CLAIMANTS IN ANY LAWSUIT, INCLUDING, BUT NOT LIMITED TO, CLASS ACTION LAWSUITS INVOLVING ANY SUCH DISPUTE.",
					"(i) Binding Arbitration. All disputes arising out of or in connection with this contract, or in respect of any defined legal relationship associated therewith or derived therefrom, shall be determined by final and binding arbitration administered by the American Arbitration Association (“AAA”) under its Commercial Arbitration Rules and Mediation Procedures (“Commercial Rules”).",
					"There shall be one arbitrator agreed to by the parties within twenty (20) days of receipt by respondent(s) of the request for arbitration or in default thereof appointed by the AAA in accordance with its Commercial Rules.",
					"The place of arbitration shall be Baton Rouge, State of Louisiana, USA.",
					"(ii) Arbitration Fees. Each party will cover its own fees and costs associated with the arbitration proceedings; however, if the arbitrator finds that you cannot afford to pay the fees and costs reasonably associated with the arbitration proceedings, we will pay them for you.",
					"(iii) Award Enforcement. The award of the arbitrator will be final and binding, and any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. The parties agree that they will not appeal any arbitration decision to any court.",
					"(iv) Our Equitable Remedies. Notwithstanding the foregoing, we may seek and obtain injunctive relief in any jurisdiction in any court of competent jurisdiction, and you agree that these Terms are specifically enforceable by us through injunctive relief and other equitable remedies without proof of monetary damages.",
					"17. GENERAL",
					"(i) Entire Agreement. These Terms and our Privacy Policy constitute the entire legal agreement between you and us and will be deemed to be the final and integrated agreement between you and us and govern your access to and use of the Platform, and completely replace any prior or contemporaneous agreements between you and us related to your access to or use of the Platform, whether oral or written.",
					"(ii) No Third-Party Beneficiaries. These Terms do not and are not intended to confer any rights or remedies upon any person or entity other than you.",
					"(iii) Interpretation. The language in these Terms will be interpreted as to its fair meaning, and not strictly for or against any party.",
					"(iv) Severability. Should any part of these Terms be held invalid, illegal, void or unenforceable, that portion will be deemed severed from these Terms and will not affect the validity or enforceability of the remaining provisions of these Terms.",
					"(v) No Waivers. Our failure or delay to exercise or enforce any right or provision of these Terms will not constitute or be deemed a waiver of future exercise or enforcement of such right or provision. The waiver of any right or provision of these Terms will be effective only if in writing and signed for and on behalf of us by a duly authorized representative.",
					"(vi) Governing Law. All matters arising out of or relating to these Terms will be governed by and construed in accordance with the laws of the State of Louisiana and the federal laws of the United States of America applicable therein without giving effect to any choice or conflict of law provision or rule (whether of the State of Louisiana or any other jurisdiction).",
					"(vii) Venue. Subject to Section 16 of these Terms, any legal action or proceeding arising under these Terms will be brought exclusively in the state and federal courts located in the State of Louisiana, and we and you irrevocably consent and attorn to the personal jurisdiction and venue there.",
					"(viii) Notices. We may provide you with any notices (including, without limitation those regarding changes to these Terms) by email or postings on the Platform. By providing us with your email address, you consent to our using the email address to send you any notices. Notices sent by email will be effective when we send the email, and notices we provide by posting will be effective upon posting. It is your responsibility to keep your email address current.",
					"(ix) Assignment. You may not assign any of your rights or obligations under these Terms, whether by operation of law or otherwise, without our prior written consent. We may assign our rights and obligations under these Terms in our sole discretion to an affiliate, or in connection with an acquisition, sale or merger."
				]
			},
			{
				title: "Privacy Policy",
				content: [
					"Last Modified: August 16, 2024",
					"Welcome to our Privacy Policy! It’s great that you want to understand how we keep your information safe.",
					"What is this Policy all about?",
					"This Privacy Policy is issued on behalf of OnFire Athletes. For the purposes of this Privacy Policy when we use “we”, “us” or “our”, we are talking about OnFire Athletes. We created this privacy policy to show our commitment to our users’ privacy. The following describes how we treat information received about subscribers and visitors (“you”) when they subscribe to or visit our digital services (“Platform”).",
					"What personal data does OnFire Athletes collect?",
					"General: When you interact with our Platform or when you contact us, we will collect “personally identifiable” information and “non-personally identifiable” information from you.",
					"We do not knowingly collect personally identifiable information from children under the age of thirteen.",
					"Personally Identifiable Information: this is information that we collect from you such as your name, telephone number, and e-mail address. This may also include billing information such as postal address.",
					"Non-Personally Identifiable Information: this is information that we collect from you that cannot be used to identify or contact you, such as your site browsing patterns or demographic information.",
					"How does OnFire Athletes collect personal data?",
					"Personally Identifiable Information: We collect this information when you actively give us this information. Examples of this include when you become a subscriber (whether on a regular or trial basis), respond to polls and surveys, provide feedback, and request information.",
					"Non-Personally Identifiable Information: We collect this type of information from you by tracking your use of our Platform, often through the use of cookies.",
					"Cookies are small data files that your browser places on your computer or device. A cookie itself does not contain or collect information. However, when it is read by a server via a web browser it can help a website deliver a more user-friendly service—for example, remembering previous purchase or account details.",
					"For more information about cookies and how to manage them, please read our full Cookie Policy.",
					"How does OnFire Athletes use personal data?",
					"Personally Identifiable Information: We use this information for customer service, such as providing you with information you request, sending you our e-mail publication, or other information we think may be interested in, and to contact you regarding your account with us.",
					"We also use this information for internal research purposes. This allows us to better understand your needs and to provide you with better service.",
					"Non-Personally Identifiable Information: We sometimes use this type of information to improve our Platform and to enable us to personalize your experience. We may also use this information to analyze how visitors and subscribers use and navigate our Platform, as well as to offer you products, programs, or services.",
					"Additionally, we may make your personally identifiable information non- personally identifiable, either by combining it with information about other individuals, or by removing characteristics (such as your name) that make the information personally identifiable to you (de-personalizing your information).",
					"How does OnFire Athletes share personal data with others?",
					"We may use third-party companies to perform services on our behalf, such as managing a part of our Platform or sending an e-mail to you. These third-party companies may be supplied with or have access to your personally identifiable information for the purpose of providing these services to us or on our behalf.",
					"These third-party companies are required to protect this information in a manner that is consistent with this Privacy Notice. They may not use this information for any purpose other than to carry out the services they are performing for us and as otherwise required by law.",
					"We may disclose and use your information in special circumstances where we believe in good faith that such disclosures: (a) are required by law; (b) will help to enforce our Terms of Use Agreement; or (c) protect your safety or security, including your property; and/or, protect the safety and security us, our Platform, and/or third parties, including property that belongs to us or third parties.",
					"If all our business assets are transferred to or acquired by another company, your information may be one of the transferred assets. How does OnFire Athletes secure personal data?",
					"The personally identifiable information that we collect about you is stored in limited access servers, password-protected and accessible by only a limited number of our personnel. We will maintain additional safeguards to protect the security of your personally identifiable information.",
					"Although we take these measures to protect the security of your information, no security measures are perfect and we cannot guarantee the security of any information you provide to us. You transfer such information at your own risk and agree that we will not be liable for any damages or injury that may result from unauthorized access to or use of your information.",
					"How can I access or correct my personal data?",
					"For instructions on how to access your personally identifiable information that this Platform has collected, and to correct factual errors in such information, please send us an email at support@onfireathletes.com.",
					"To protect your privacy and security, we will take reasonable steps to help verify your identity before granting access or making corrections.",
					"How can I contact OnFire Athletes?",
					"If you have any questions or concerns about our Privacy Policy, please contact us by sending an email to support@onfireathletes.com .",
					"How will I know if this Privacy Policy changes?",
					"We reserve the right to change or remove this Privacy Policy upon ten days’ prior notice. If we decide to change or remove this Privacy Policy, we will post these changes here. We encourage you to visit this page frequently to stay informed.",
					"Changes to this Privacy Policy may affect our use of personal information that you provided us prior to our notification to you of the changes. If you do not wish to permit changes in our use of your information, you must notify us prior to the effective date of the changes.",
					"Other disclosures",
					"Links",
					"Our Platform may contain links to other sites whose information practices may be different than ours. We are not responsible or liable for the information collection practices or content of such linked sites. Visitors should consult the other sites’ privacy notices, as we have no control over information that is submitted to, or collected by, these third parties."
				]
			},
			{
				title: "Cookie Policy",
				content: [
					"Last Modified: August 16, 2024",
					"OnFire Athletes uses cookies on its website and our digital applications.",
					"This Cookie Policy describes our policy with respect to information, including information that can be associated with a specific person and could be used to identify that person (\"Personal Data\"), that is collected from Users through cookies, pixel tags, local shared objects, web storage and other similar technologies.",
					"Please also refer to our Privacy Policy (incorporated by reference), which details our policy with respect to the collection, use, disclosure, transfer and storage of information, including Personal Data, that is collected from Users. Nothing in this Cookie Policy shall be deemed to modify, waive, amend or rescind any other term of the Privacy Policy.",
					"Consent",
					"By using our digital platform (“Platform”), you are consenting to the use of the technologies described in this Cookie Policy to collect both Personal Data and non-Personal Data and to the storage of information on your device or web browser as described in this Cookie Policy. What are cookies, pixel tags (AKA clear GIFs or web beacons), local shared objects, and web storage?",
					"Cookies",
					"Cookies are small data files that your browser sets on your computer or device. A cookie itself does not contain or collect information. However, when it is read by a server via a web browser, it can help a website deliver a more user-friendly service—for example, remembering previous purchases or account details.",
					"Pixel Tags (aka Clear GIFs or Web Beacons).",
					"A pixel tag is a tiny invisible tag or graphic placed on certain parts of our Platform, in emails or in certain other downloadable content, but not on your computer, mobile device or browser, unless you download the content that contains such tags.",
					"Local Shared Objects (aka Flash Cookies).",
					"A local shared object is like a cookie, except it is stored on your computer or mobile device, instead of your browser, and it can store more than just text. The methods for controlling local shared objects are different than the methods for controlling cookies (as discussed below).",
					"How can I manage these technologies?",
					"Cookies",
					"Cookies may be session cookies (meaning they last only for one browser session) or persistent cookies (meaning they continue on your browser until they are deleted). You can manage cookies through your web browser's option settings and through those settings you may be able (a) to receive notifications when you are receiving new cookies; (b) to disable cookies; or (c) to delete cookies. Please refer to your web browser's help section for information on how to do this.",
					"Pixel Tags",
					"Pixel tags do not store information on your computer, mobile device or browser (although they are occasionally downloaded to your computer if contained in an email or other downloadable content) so they cannot be managed by you except by deleting the content in which the tag is contained.",
					"Local Shared Objects",
					"Local shared objects are stored on your computer or mobile device.",
					"Web Storage",
					"Web Storage, or HTML5 Local Storage, is an industry-standard data storage technology that is implemented by internet browser providers. Refer to your browser's help contents for procedures on how to manage settings for Web Storage.",
					"The Technologies used by OnFire Athletes fall into four categories.",
					"Essential (necessary)",
					"We use these technologies to enable technical site functionality and to provide services explicitly requested by you, like your personal preferences, and for security and fraud prevention.",
					"Performance/Analytics",
					"We use these technologies to collect information about how visitors use and experience our website to optimize design, operations, efficiency and to improve your user experience. For example, we may place cookies that allow us (a) to measure the time of your requests to our servers and our responses; (b) to compare new features to old ones; (c) to record statistics about Platform usage; (d) to track your activities on our Platform; and (e) to track the places from which you come to our Platform. We may also use third party cookies to collect information about visitor behavior on our Platform for these Performance/Analytics purposes.",
					"Functionality",
					"We use these technologies to allow us to provide certain functionality to our Platform and to remember your preferences. For instance, when you click the \"remember me\" box on our log in page we place a persistent cookie on your browser that allows our Services to pre-populate your username when you return.",
					"Advertising",
					"We may use these technologies to deliver advertisements to you both on and off our Platform. By using these technologies we expect to better shape any advertisements to your interests. Sometimes this is called online behavioral, interest based or retargeted advertising. In the event we engage in a third- party service provider for these technologies, we will update our policy to let you know who they are. You can manage your opt-outs for those third-party service providers who participate in such opt-out frameworks. Not every one of these third-party service providers may always participate in every voluntary framework, so you may need to access their individual opt out frameworks so you can control your preferences directly with those providers.",
					"Does anybody else use these technologies on your services?",
					"Most of the cookies and other technologies described above on our Services are set by us (aka first-party cookies) or are used in connection with our Platform and set by third-party service providers at our direction (\"Third Party Cookies\"). We may use Third Party Cookies with respect to each of the uses detailed above."
				]
			}
		],
	};
}
