name: Deploy Gamechangers Production Backend

on:
    push:
        branches: [ "production" ]

jobs:
    build:
        name: Deploy Production Backend
        runs-on: self-hosted
        defaults:
            run:
                working-directory: backend/gamechangers-backend/

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install --os=linux --cpu=x64 sharp -f

            - name: Change stage to production
              run: yq -i '.provider.stage = "production"' serverless.yml

            - name: Deploy to AWS
              run: sls deploy