name: Test Backend Deployment

on:
    push:
        branches: [ "main" ]
        paths:
          - "backend/**"
    pull_request:
        branches: [ "main" ]
        paths:
          - "backend/**"

jobs:
    build:
        name: Deploy Backend
        runs-on: self-hosted
        defaults:
            run:
                working-directory: backend/gamechangers-backend/

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm i -f

            - name: Change stage 
              run: yq -i '.provider.stage = "zenith-mac-test-${{ github.run_number }}"' serverless.yml

            - name: Deploy to AWS
              run: sls deploy
            
            - name: Remove deployment
              run: sls remove